/** Cosmetic balls. Looks and trails never change slide rules, par, or hints. */

export const BALLS = [
  {
    id: "oak",
    name: "Oak",
    price: 0,
    blurb: "Carved oak ball and a knot-hole goal.",
    trail: null,
    motion: null,
    goal: "knot",
  },
  {
    id: "dune",
    name: "Dune",
    price: 20,
    blurb: "Sand-colored ball. The goal is a clay oasis ring.",
    trail: null,
    motion: null,
    goal: "oasis",
  },
  {
    id: "marble",
    name: "Marble",
    price: 6,
    blurb: "A glass swirl. The goal is a crystal dish.",
    trail: "sparkle",
    motion: null,
    goal: "crystal",
  },
  {
    id: "soccer",
    name: "Soccer",
    price: 12,
    blurb: "The hole wears a goal net.",
    trail: null,
    motion: null,
    goal: "net",
  },
  {
    id: "tire",
    name: "Tire",
    price: 18,
    blurb: "Black tread that stamps the floor. The goal is a rubber ring.",
    trail: "tire",
    motion: null,
    goal: "rim",
  },
  {
    id: "slime",
    name: "Slime",
    price: 24,
    blurb: "Wobbles along and leaves green splats. The goal is a puddle.",
    trail: "splat",
    motion: "wobble",
    goal: "puddle",
  },
  {
    id: "snow",
    name: "Snowball",
    price: 30,
    blurb: "Grows a little as it rolls. The goal is a snowman.",
    trail: null,
    motion: "grow",
    goal: "snowman",
  },
  {
    id: "basketball",
    name: "Basketball",
    price: 32,
    blurb: "Bounces on the way. The hole becomes a hoop.",
    trail: null,
    motion: "bounce",
    goal: "hoop",
  },
  {
    id: "beach",
    name: "Beach",
    price: 42,
    blurb: "Striped ball. The goal is a bucket.",
    trail: null,
    motion: null,
    goal: "bucket",
  },
  {
    id: "bowling",
    name: "Bowling",
    price: 48,
    blurb: "Lands with a thud. Pins stand at the hole.",
    trail: null,
    motion: "thud",
    goal: "pins",
  },
  {
    id: "meteor",
    name: "Meteor",
    price: 54,
    blurb: "Flame trail. The goal is a crater.",
    trail: "flame",
    motion: null,
    goal: "crater",
  },
  {
    id: "toy",
    name: "Toy",
    price: 56,
    blurb: "A bright toy ball on a painted pedestal.",
    trail: null,
    motion: null,
    goal: "pedestal",
  },
  {
    id: "mushroom",
    name: "Mushroom",
    price: 64,
    blurb: "A cap-colored ball. The goal is a stump.",
    trail: null,
    motion: null,
    goal: "stump",
  },
  {
    id: "gummy",
    name: "Gummy",
    price: 72,
    blurb: "A jelly ball. The goal is a candy dish.",
    trail: null,
    motion: null,
    goal: "dish",
  },
  {
    id: "coco",
    name: "Coconut",
    price: 96,
    blurb: "A jungle ball. The goal is a vine nest.",
    trail: null,
    motion: null,
    goal: "nest",
  },
  {
    id: "alien",
    name: "Alien",
    price: 120,
    blurb: "Purple goo. The goal is a glowing ring.",
    trail: null,
    motion: null,
    goal: "glow",
  },
  {
    id: "gear",
    name: "Gear",
    price: 150,
    blurb: "A metal ball. The goal is a toothed ring.",
    trail: null,
    motion: null,
    goal: "cog",
  },
  {
    id: "baseball",
    name: "Baseball",
    price: 36,
    blurb: "Red stitches. The goal is a home plate.",
    trail: null,
    motion: null,
    goal: "plate",
  },
  {
    id: "tennis",
    name: "Tennis",
    price: 40,
    blurb: "Felt ball that bounces. The goal is a cup.",
    trail: null,
    motion: "bounce",
    goal: "cup",
  },
  {
    id: "golf",
    name: "Golf",
    price: 46,
    blurb: "Dimples. The goal is a flag cup.",
    trail: null,
    motion: null,
    goal: "flag",
  },
  {
    id: "yarn",
    name: "Yarn",
    price: 68,
    blurb: "Thread unravels behind it and the ball shrinks. Resets each stage. The goal is a spool.",
    trail: "yarn",
    motion: "yarn",
    goal: "spool",
  },
  {
    id: "donut",
    name: "Donut",
    price: 78,
    blurb: "Sprinkles on the way. The goal is a coffee cup.",
    trail: "sprinkle",
    motion: null,
    goal: "mug",
  },
  {
    id: "melon",
    name: "Watermelon",
    price: 88,
    blurb: "Seeds drop. It splits with juice at the goal.",
    trail: "seed",
    motion: null,
    goal: "rind",
  },
  {
    id: "disco",
    name: "Disco",
    price: 108,
    blurb: "Mirror tiles and light flecks. The goal is a tiny mirror ball.",
    trail: "fleck",
    motion: null,
    goal: "lamp",
  },
  {
    id: "lucky",
    name: "Lucky pouch",
    price: 128,
    blurb: "Coin sparkles. The goal is a pile of coins.",
    trail: "coin",
    motion: null,
    goal: "hoard",
  },
  {
    id: "cat",
    name: "Cat furball",
    price: 138,
    blurb: "Fur puffs. A paw taps it into the goal.",
    trail: "fur",
    motion: null,
    goal: "paw",
  },
  {
    id: "pixel",
    name: "8-bit",
    price: 168,
    blurb: "Pixel afterimages. The goal is a stack of blocks.",
    trail: "pixel",
    motion: null,
    goal: "pixels",
  },
  {
    id: "globe",
    name: "Globe",
    price: 188,
    blurb: "Continents turn. A small rocket waits at the goal.",
    trail: null,
    motion: null,
    goal: "rocket",
  },
  {
    id: "skull",
    name: "Skull",
    price: 210,
    blurb: "Purple smoke. The goal is a cauldron.",
    trail: "smoke",
    motion: null,
    goal: "cauldron",
  },
];

export function ballById(id) {
  return BALLS.find((ball) => ball.id === id) || BALLS[0];
}
